import Foundation
import RecallCore

/// Decides whether a clip from a given app may be captured at all.
///
/// The built-in list covers password managers, keychains and authenticator apps: copies
/// from these are dropped before they are read, not stored and then filtered.
public struct AppExclusionPolicy: Sendable {
    /// Bundle identifiers excluded out of the box.
    public static let builtInBundleIDs: Set<String> = [
        // 1Password
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.1password.browser-support",
        // Bitwarden
        "com.bitwarden.desktop", "com.8bit.bitwarden",
        // Apple Keychain / Passwords
        "com.apple.keychainaccess", "com.apple.Passwords", "com.apple.PasswordManager",
        // Other managers and authenticators
        "com.lastpass.LastPass", "com.dashlane.dashlanephonefinal", "in.sinew.Enpass-Desktop",
        "com.keepassium.mac", "org.keepassxc.keepassxc", "com.jetbrains.toolbox.password",
        "com.authy.authy-mac", "com.stephenradford.Authenticator", "com.mattrubin.authenticator",
        "com.strongbox.mac.strongbox", "com.nordpass.mac", "com.protonvpn.mac.pass",
        "me.proton.pass.electron", "com.secretive.Secretive",
    ]

    /// Pasteboard types that mean "do not record this", honoured by well-behaved apps.
    /// These are checked by the capture layer; listed here so the policy is in one place.
    public static let concealedPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    private let userExcluded: Set<String>

    public init(userExcludedBundleIDs: Set<String> = []) {
        self.userExcluded = userExcludedBundleIDs
    }

    public init(settings: RecallSettings) {
        self.init(userExcludedBundleIDs: settings.userExcludedBundleIDs)
    }

    public var excludedBundleIDs: Set<String> {
        Self.builtInBundleIDs.union(userExcluded)
    }

    public func isExcluded(bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        return excludedBundleIDs.contains(bundleIdentifier)
    }

    public func isExcluded(_ source: SourceApp?) -> Bool {
        isExcluded(bundleIdentifier: source?.bundleIdentifier)
    }

    /// True when any of the pasteboard's types asks us to stay out of it.
    public func isConcealed(pasteboardTypes: some Sequence<String>) -> Bool {
        pasteboardTypes.contains { Self.concealedPasteboardTypes.contains($0) }
    }
}
